name: FastAPI CI/CD

on:
  #Trigger the workflow on push
  push:
    branches:
      - main


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
    
      #Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      # Setup Python Virtual Venv
      - name: Install Python Virtual Venv
        run: pip3 install virtualenv

      # Setup Virtual ENV

      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Build a Virtual ENV, but inly if it doesn't already exist

      - name: Activate Virtual ENV
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt

      - name: Run Tests
        run: . venv/bin/activate && pytest
      
      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.8/site-packages
          zip -r9 ../../../../api.zip .
      
      - name: Add API files to ZIP file
        run: cd ./api && zip -g ../api.zip -r .
      
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Download Lambda api.zip
        uses: actions/download-artifact@v2
        with:
          name: api
      - name: Upload To S3
        run: aws s3 cp api.zip s3://fastapigithubactions/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy New Lambda
        run: aws lambda update-function-code --function-name fastapi --s3-bucket fastapigithubactions --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      





